#!/bin/bash

echo "🚀 FOOTBALL ANALYTICS - DÉPLOIEMENT EN LIGNE"
echo "============================================="

echo ""
echo "🎯 MÉTHODE 1: STREAMLIT CLOUD (RECOMMANDÉE - GRATUIT)"
echo "-----------------------------------------------------"
echo "✅ Votre code est déjà sur GitHub"
echo "1. Aller sur: https://share.streamlit.io"
echo "2. Se connecter avec votre compte GitHub"
echo "3. Cliquer 'New app'"
echo "4. Repository: Abdel67Unistra/Intelligence-football-analytics"
echo "5. Branch: main"
echo "6. Main file path: python_analytics/dashboards/coach_interface.py"
echo "7. Cliquer 'Deploy!'"
echo ""
echo "⏱️  Temps de déploiement: 2-3 minutes"
echo "🔗 URL finale: https://your-app-name.streamlit.app"

echo ""
echo "🎯 MÉTHODE 2: RAILWAY (GRATUIT AVEC LIMITATIONS)"
echo "------------------------------------------------"
echo "1. Aller sur: https://railway.app"
echo "2. Se connecter avec GitHub"
echo "3. 'New Project' → 'Deploy from GitHub repo'"
echo "4. Sélectionner votre repository"
echo "5. Railway détecte automatiquement railway.toml"
echo "6. Déploiement automatique"

echo ""
echo "🎯 MÉTHODE 3: RENDER (GRATUIT AVEC LIMITATIONS)"
echo "-----------------------------------------------"
echo "1. Aller sur: https://render.com"
echo "2. Se connecter avec GitHub"
echo "3. 'New' → 'Web Service'"
echo "4. Connecter votre repository"
echo "5. Nom: football-analytics"
echo "6. Build Command: pip install -r requirements_streamlit.txt"
echo "7. Start Command: streamlit run python_analytics/dashboards/coach_interface.py --server.port=\$PORT --server.address=0.0.0.0"

echo ""
echo "🎯 MÉTHODE 4: HEROKU (PAYANT MAIS PUISSANT)"
echo "-------------------------------------------"
echo "1. Installer Heroku CLI"
echo "2. heroku login"
echo "3. heroku create football-analytics-app"
echo "4. git push heroku main"
echo "5. heroku open"

echo ""
echo "🎯 MÉTHODE 5: DOCKER + CLOUD"
echo "----------------------------"
echo "1. docker build -t football-analytics ."
echo "2. docker run -p 8501:8501 football-analytics"
echo "3. Puis déployer sur AWS/GCP/Azure"

echo ""
echo "📋 FICHIERS CRÉÉS POUR LE DÉPLOIEMENT:"
echo "  ✅ requirements_streamlit.txt (dépendances allégées)"
echo "  ✅ Procfile (pour Heroku)"
echo "  ✅ Dockerfile (pour containers)"
echo "  ✅ railway.toml (pour Railway)"
echo "  ✅ .streamlit/config.toml (configuration)"

echo ""
echo "🏆 RECOMMANDATION FINALE:"
echo "=========================="
echo "🥇 1er choix: STREAMLIT CLOUD (100% gratuit, facile)"
echo "🥈 2ème choix: RAILWAY (gratuit avec limitations)"
echo "🥉 3ème choix: RENDER (gratuit avec limitations)"

echo ""
echo "🔗 VOTRE REPOSITORY:"
echo "https://github.com/Abdel67Unistra/Intelligence-football-analytics"

echo ""
echo "💡 APRÈS DÉPLOIEMENT:"
echo "- Partagez l'URL avec vos collègues"
echo "- Mettez à jour en pushant sur GitHub"
echo "- Surveillez les métriques d'usage"

echo ""
echo "🎉 Votre plateforme sera accessible 24h/24 en ligne !"
